### PR TITLE
[feat] allow GLBufferAttribute as an attribute type

### PR DESCRIPTION
**Pull request by mikkom**
### Why

The current typings don't allow setting `GLBufferAttribute` as an attribute in `BufferGeometry`. This functionality has been in Three.js for quite some time (originally introduced in https://github.com/mrdoob/three.js/pull/13196 back in 2020).

Three.js master continues to support this feature in `BufferGeometry` (see e.g. https://github.com/mrdoob/three.js/blob/master/src/core/BufferGeometry.js#L371), documents the attribute type in https://threejs.org/docs/#api/en/core/GLBufferAttribute and has a usage example in https://github.com/mrdoob/three.js/blob/master/examples/webgl_buffergeometry_glbufferattribute.html#L115-L117.

### What

This change adds `GLBufferAttribute` as a valid type for `setAttribute` and `getAttribute` methods in `BufferGeometry`. The type for `GLBufferAttribute` had already been defined and exported but it was not used anywhere else in the typings.

Note that the change can break consumers of the typings as `GLBufferAttribute` does not implement the same interface as `BufferAttribute`. The way to fix these issues is to use the boolean flags (`isBufferAttribute`, `isInterleavedBufferAttribute`, or `isGLBufferAttribute`) to discriminate between the different options (or alternatively by resorting to type assertions). Despite the potential breakage, I believe these typings are more correct.

### Checklist

-   [x] Checked the target branch (current goes `master`, next goes `dev`)
-   [x] Added myself to contributors table
-   [x] Ready to be merged

### CODE REVIEW

File: types/three/src/core/BufferAttribute.d.ts [hunk 1]
```diff
@@ -43,6 +43,8 @@ export class BufferAttribute {
     set needsUpdate(value: boolean);
 
     readonly isBufferAttribute: true;
+    readonly isInterleavedBufferAttribute: false;
+    readonly isGLBufferAttribute: false;
```
Comment (0b5vr) [inline types/three/src/core/BufferAttribute.d.ts]: I don't think these `false` are explicitly set.

File: types/three/src/core/GLBufferAttribute.d.ts [hunk 2]
```diff
@@ -5,13 +5,19 @@
 export class GLBufferAttribute {
     constructor(buffer: WebGLBuffer, type: number, itemSize: number, elementSize: 1 | 2 | 4, count: number);
 
+    /**
+     * @default ''
+     */
+    name: string;
```
Comment (0b5vr) [inline types/three/src/core/GLBufferAttribute.d.ts]: where is it set?

**Review by 0b5vr — CHANGES_REQUESTED** [review]
Check 2 comments I left. Otherwise it looks good to me.

File: types/three/src/core/GLBufferAttribute.d.ts (hunk 2 above)
Comment (mikkom) [reply types/three/src/core/GLBufferAttribute.d.ts]: Good point. For whatever reason the name property isn't initialized as an empty string in `GLBufferAttribute` even though both the other attribute types do that. I'll remove the comment and the property (even though this adds risk of further breakage if people are relying on using the name property on attributes...).

File: types/three/src/core/BufferAttribute.d.ts (hunk 1 above)
Comment (mikkom) [reply types/three/src/core/BufferAttribute.d.ts]: True that. Should I rather set these as `undefined` instead of `false`? If we omit these fields completely then we no longer can use them to discriminate between the different attribute types.

File: types/three/src/core/GLBufferAttribute.d.ts (hunk 2 above)
Comment (mikkom) [reply types/three/src/core/GLBufferAttribute.d.ts]: Another option would be to set the field as
```
    /**
     * @default undefined
     */
    name?: string;
```

File: types/three/src/core/BufferAttribute.d.ts (hunk 1 above)
Comment (0b5vr) [reply types/three/src/core/BufferAttribute.d.ts]: Ok that's the motivation, I got it.
You want to use `position.isGLBufferAttribute` here right?

https://github.com/three-types/three-ts-types/blob/9ce3aa43d8b9af2d63217cd9dfa177d7ae4edcbe/types/three/test/controls/controls-pointercontrols.ts#L129

But having `false` here only for this is lying since it isn't actually `false`.

You can solve this by either of these 3 solutions:

1. use `!(position instanceof GLBufferAttribute)` instead for the condition
2. use `'setXYZ' in position` instead for the condition
3. type assert the `position`, `let position = floorGeometry.attributes.position as BufferAttribute;`

I prefer the (3), since it's obvious that the `position` is `BufferAttribute` here since it's made by `new THREE.PlaneGeometry()`.

File: types/three/src/core/GLBufferAttribute.d.ts (hunk 2 above)
Comment (0b5vr) [reply types/three/src/core/GLBufferAttribute.d.ts]: I agree that it's weird `GLBufferAttribute` doesn't have `name` on the Three.js side.
But, if it's not appeared in the Three.js source yet, it should not be added here I think.

> (even though this adds risk of further breakage if people are relying on using the name property on attributes...)

That's actually a good point.
I feel like we have to ask Three.js side about `GLBufferAttribute.name` first.

> Another option would be to set the field as
> 
> ```
>     /**
>      * @default undefined
>      */
>     name?: string;
> ```

I choose this if Three.js side says `GLBufferAttribute.name` should exist.

@mikkom Would you ask about this somewhere? I would choose [Discourse](https://discourse.threejs.org/).

**Comment by 0b5vr** [comment]
You did it on Three.js side, wooo! Thank you!

File: types/three/src/core/GLBufferAttribute.d.ts (hunk 2 above)
Comment (0b5vr) [reply types/three/src/core/GLBufferAttribute.d.ts]: You did it on Three.js side, wooo! Thank you! Now it's valid to say the `.name` (in the next revision, r149).

Comment (mikkom) [reply types/three/src/core/GLBufferAttribute.d.ts]: Heh yeah, finally got to pushing this forward :)  I think I should now retarget this PR against dev instead of master, right?

File: types/three/src/core/BufferAttribute.d.ts (hunk 1 above)
Comment (mikkom) [reply types/three/src/core/BufferAttribute.d.ts]: To me it seems that it would be most natural to use the publicly documented boolean fields (e.g. https://threejs.org/docs/#api/en/core/BufferAttribute.isBufferAttribute) for checking this. So my suggestion would be to still  change the `false` values to `undefined` and then the types would precisely match the returned values. If we omit the non-true fields from TS types then it's not possible to refer to the boolean field unless you already have the corresponding attribute type. And then there's no longer any point in checking a trivially true field :)

The three solutions you listed above definitely do work and nothing prevents the user from choosing any of them. And I agree that in many cases a type assertion can be the most straightforward option. I just think that it would be better to support the documented fields in a meaningful way in TS, as well. WDYT?
