### ISSUE TITLE
[@types/three] v0.180.0+ Type path conflict causes "Object3D is not assignable" errors

### ISSUE THREAD

**Issue by Suprhimp** [three-types/three-ts-types#1888]
I don't know where do I leave this issue.. but please check :)

### Description
Starting from `@types/three@0.180.0`, TypeScript incorrectly treats `Object3D` types from different
import paths as incompatible types, causing compilation errors even when the types are structurally
identical.

### Affected Versions
- ✅ Works: `@types/three@0.175.0`
- ❌ Broken: `@types/three@0.180.0`
- ❌ Broken: `@types/three@0.181.0`

### Error Example
```typescript
Type 'Group<Object3DEventMap>' is not assignable to parameter of type 'Object3D<Object3DEventMap>'.
  Type 'Group<Object3DEventMap>' is missing the following properties from type
'Object3D<Object3DEventMap>':
  setPointerCapture, releasePointerCapture, hasPointerCapture
```
Note: These DOM methods don't exist on Object3D - this is a symptom of TypeScript treating paths as
different types.

Root Cause

The package exports types through multiple paths:
- node_modules/@types/three/src/core/Object3D.d.ts
- node_modules/@types/three/build/three.module.d.ts

TypeScript treats these as distinct types even though three.module.d.ts re-exports from src/Three.js.

Reproduction
```
import * as THREE from 'three';
import { Group } from 'three';

function processObject(obj: THREE.Object3D) {
  console.log(obj);
}

const group = new Group();
processObject(group); // ❌ Error in 0.180.0+, ✅ Works in 0.175.0
```
Environment

- TypeScript: 5.7.3
- Module resolution: NodeNext
- Package manager: pnpm 10.4.1
- Used with: @react-three/fiber, @react-three/drei

Workaround

Downgrade to @types/three@0.175.0:
{
  "overrides": {
    "@types/three": "0.175.0"
  }
}

Expected Behavior

All Object3D types should be interchangeable regardless of import path, as they were in v0.175.0.

Additional Context

This issue appears when using:
- Namespace imports: import * as THREE from 'three'
- Named imports: import { Object3D } from 'three'
- Mixed usage across the codebase

The error messages reference DOM Element methods (setPointerCapture, etc.) which don't exist on
Object3D, suggesting TypeScript's type comparison is failing at a fundamental level.

**Comment by Methuselah96** [comment]
I'm not able to reproduce the issue, here is your code sample working in the [TypeScript Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wCoAkBKBRPOAMyghDgHIYALKAUzooG4BYAKFEljgG84BxUgFcwcAL7FS5KrQbN27IkIB2AYxjAIyuGFKq6qVAHkARgCs66gBQRzALky4CAOlMX1AZgAiASl7s4OFUtVAgAGzpnMIgAcxtzH1Y2MQU2YOVUeBjhUQBeOGU6AHcBHKtE9l0IfUM3SxgrbIgRRLgAeja4QBlyODwoUig4YG0ABmcARgAOMZGAagAaOEBQcjgAdWgAa3RhuDHxgHYAVmcR9iA)

**Comment by Methuselah96** [comment]
Closing since I'm not able reproduce the issue, let me know if there's anything else I can do to help
